update some type annotations
mitodl/course-search-utils pull request #26
Opened 2022-01-11 14:40 UTC by alicewriteswrongs

This basically

- makes all the properties on the `Facets` interface optional, since we 1) treat them as such (we do a lot of `facets.whatever ?? []` before we do anything with the data) and 2) I'm working on porting over the ocw-www search code to Typescript and the existing type signatures don't play well with how we use it over there
- create a new `LearningResourceType` enum which is exported and can be then re-used elsewhere

2022-01-13 17:22 UTC, abeglova requested changes
This pr currently breaks ocw-hugo-themes since ocw-hugo-themes imports LR_TYPE_COURSE from course-search-utils here:
https://github.com/mitodl/ocw-hugo-themes/blob/4c016ffec1f5d19fc5a9277abb03a9a91ee06e6d/www/assets/js/components/SearchResult.test.js#L7

2022-01-14 17:21 UTC, alicewriteswrongs commented
yes, that's intentional, once this is merged and deployed I'll introduce a PR to fix that in ocw-hugo-themes

2022-01-21 19:51 UTC, alicewriteswrongs commented
@abeglova any chance you could take another look at this?

2022-01-21 19:54 UTC, abeglova approved these changes
👍

2022-01-21 20:20 UTC, alicewriteswrongs commented
thanks!

2022-01-21 20:23 UTC, merged